variables:
  DEBIAN_FRONTEND: noninteractive
  NODE_VERSION: "18"

.yarn_ready: &yarn
  image: node:$NODE_VERSION
  before_script:
    - corepack enable
    - yarn --version

build:
  <<: *yarn
  stage: build
  variables:
    NODE_ENV: production
  script:
    - yarn install
    - yarn build
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - build/
  tags:
    - docker

pages:
  stage: deploy
  environment:
    name: prod
    url: $PUBLIC_URL
  variables:
    GIT_STRATEGY: none
  script:
    - mv build public
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - public
  tags:
    - docker
  only:
    - master
